-- Problem: Running Portfolio Value
-- Calculate the running total portfolio value for each account over time, showing date, account_id, transaction amount, and cumulative portfolio value. Order by account and date.
SELECT 
    transaction_date AS date,
    account_id,
    total_amount AS transaction_amount,
    SUM(total_amount) OVER (PARTITION BY account_id ORDER BY transaction_date) AS cumulative_portfolio_value
FROM transactions
ORDER BY account_id, transaction_date;

-- Problem: Transaction Ranking by Volume
-- For each trader, rank their transactions by total amount within each month of 2024. Show trader_name, month, transaction details, amount, and rank. Only show the top 3 transactions per trader per month.
WITH RankedTransactions AS (
    SELECT 
        t.trader_id,
        tr.trader_name,
        DATE_FORMAT(transaction_date, '%Y-%m') AS month,
        t.transaction_id,
        t.total_amount,
        RANK() OVER (PARTITION BY t.trader_id, DATE_FORMAT(transaction_date, '%Y-%m') ORDER BY t.total_amount DESC) AS rank
    FROM transactions t
    JOIN traders tr ON t.trader_id = tr.trader_id
    WHERE YEAR(transaction_date) = 2024
)
SELECT *
FROM RankedTransactions
WHERE rank <= 3;

-- Problem: Moving Average Price Analysis
-- Calculate 3-day and 7-day moving averages for Apple (AAPL) stock closing prices. Identify dates where the 3-day MA crosses above the 7-day MA (golden cross signal).
WITH MovingAverages AS (
    SELECT 
        price_date,
        close_price,
        AVG(close_price) OVER (ORDER BY price_date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS ma_3_day,
        AVG(close_price) OVER (ORDER BY price_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ma_7_day
    FROM market_prices mp
    JOIN securities s ON mp.security_id = s.security_id
    WHERE s.security_symbol = 'AAPL'
)
SELECT 
    price_date,
    ma_3_day,
    ma_7_day
FROM MovingAverages
WHERE ma_3_day > ma_7_day
  AND LAG(ma_3_day) OVER (ORDER BY price_date) <= LAG(ma_7_day) OVER (ORDER BY price_date);

-- Problem: Year-over-Year Growth Analysis
-- Compare quarterly revenue generated by relationship managers in 2024 vs 2023. Calculate YoY growth percentage and rank managers by growth rate.
WITH QuarterlyRevenue AS (
    SELECT 
        rm.manager_id,
        rm.manager_name,
        YEAR(t.transaction_date) AS year,
        QUARTER(t.transaction_date) AS quarter,
        SUM(t.total_amount) AS revenue
    FROM transactions t
    JOIN accounts a ON t.account_id = a.account_id
    JOIN relationship_managers rm ON a.relationship_manager_id = rm.manager_id
    WHERE YEAR(t.transaction_date) IN (2023, 2024)
    GROUP BY rm.manager_id, rm.manager_name, YEAR(t.transaction_date), QUARTER(t.transaction_date)
),
YoYGrowth AS (
    SELECT 
        r2024.manager_id,
        r2024.manager_name,
        r2024.quarter,
        ((r2024.revenue - r2023.revenue) / r2023.revenue) * 100 AS yoy_growth
    FROM QuarterlyRevenue r2024
    JOIN QuarterlyRevenue r2023
      ON r2024.manager_id = r2023.manager_id
     AND r2024.quarter = r2023.quarter
     AND r2024.year = 2024
     AND r2023.year = 2023
)
SELECT 
    manager_id,
    manager_name,
    quarter,
    yoy_growth,
    RANK() OVER (ORDER BY yoy_growth DESC) AS rank
FROM YoYGrowth;

-- Problem: Client Concentration Risk
-- For each account, calculate what percentage each security holding represents of the total portfolio value. Flag any positions exceeding 25% as "High Concentration Risk".
WITH PortfolioValues AS (
    SELECT 
        account_id,
        SUM(quantity * current_price) AS total_portfolio_value
    FROM portfolio_holdings
    GROUP BY account_id
),
ConcentrationRisk AS (
    SELECT 
        ph.account_id,
        ph.security_id,
        (ph.quantity * ph.current_price) / pv.total_portfolio_value * 100 AS holding_percentage
    FROM portfolio_holdings ph
    JOIN PortfolioValues pv ON ph.account_id = pv.account_id
)
SELECT 
    account_id,
    security_id,
    holding_percentage,
    CASE WHEN holding_percentage > 25 THEN 'High Concentration Risk' ELSE 'Normal' END AS risk_level
FROM ConcentrationRisk;

-- Problem: Compliance Event Resolution Time
-- Calculate average resolution time (in days) for compliance events by severity level. Also show the fastest and slowest resolution times for each severity, and total open cases.
SELECT 
    severity,
    AVG(DATEDIFF(resolution_date, event_date)) AS avg_resolution_time,
    MIN(DATEDIFF(resolution_date, event_date)) AS fastest_resolution_time,
    MAX(DATEDIFF(resolution_date, event_date)) AS slowest_resolution_time,
    SUM(CASE WHEN status = 'Open' THEN 1 ELSE 0 END) AS total_open_cases
FROM compliance_events
WHERE resolution_date IS NOT NULL
GROUP BY severity;

-- Problem: Margin Call Risk Assessment
-- Identify accounts with margin loans where current equity position (current holdings value minus loan outstanding) is less than 130% of loan value. Calculate the deficit amount.
WITH EquityPositions AS (
    SELECT 
        a.account_id,
        SUM(ph.quantity * ph.current_price) AS current_equity,
        l.loan_amount
    FROM accounts a
    JOIN portfolio_holdings ph ON a.account_id = ph.account_id
    JOIN loans l ON a.client_id = l.client_id
    WHERE l.loan_type = 'Margin'
    GROUP BY a.account_id, l.loan_amount
)
SELECT 
    account_id,
    current_equity,
    loan_amount,
    current_equity - (1.3 * loan_amount) AS deficit_amount
FROM EquityPositions
WHERE current_equity < 1.3 * loan_amount;

-- Problem: Suspicious Trading Pattern Detection
-- Find accounts that executed more than 10 transactions in a single day. For each flagged account, show the date, number of transactions, total volume, and whether they have any open compliance cases.
WITH DailyTransactions AS (
    SELECT 
        account_id,
        DATE(transaction_date) AS transaction_date,
        COUNT(*) AS transaction_count,
        SUM(total_amount) AS total_volume
    FROM transactions
    GROUP BY account_id, DATE(transaction_date)
    HAVING COUNT(*) > 10
)
SELECT 
    dt.account_id,
    dt.transaction_date,
    dt.transaction_count,
    dt.total_volume,
    CASE WHEN EXISTS (
        SELECT 1 FROM compliance_events ce
        WHERE ce.account_id = dt.account_id AND ce.status = 'Open'
    ) THEN 'Yes' ELSE 'No' END AS has_open_compliance_cases
FROM DailyTransactions dt;