#!/usr/bin/env python3
"""Append Q101-200 with bullet-formatted answers."""
import json, uuid
NB = "python.ipynb"
def md(s): return {"cell_type":"markdown","id":str(uuid.uuid4())[:8],"metadata":{},"source":s}

C=[
# ─── Section E: Q101-125 ───
md([
"---\n","\n",
"#### Section E: Advanced Python Concepts (Q101–125)\n",
"\n",
"| # | Question | Keywords | Answer |\n",
"|---|----------|----------|--------|\n",
"| 101 | Garbage collection? | GC, reference counting | • **Reference counting**: each object tracks refs → freed at 0<br>• **Cyclic GC**: detects circular references<br>• `gc.collect()` forces collection<br>• Most memory freed via reference counting |\n",
"| 102 | Reference counting? | refcount, memory | • Each object has a reference count<br>• `sys.getrefcount(obj)` shows count (+1 for arg)<br>• Freed immediately when count = 0<br>• Cannot detect circular references |\n",
"| 103 | Circular references? | Circular, gc, cycle | • Objects reference each other (A→B→A)<br>• Ref counting can't free these<br>• Cyclic GC periodically detects/collects<br>• Use `weakref` to break cycles |\n",
"| 104 | What is `weakref`? | weakref, gc | • Reference that doesn't prevent GC<br>• `weakref.ref(obj)` → returns None when collected<br>• `WeakValueDictionary`, `WeakKeyDictionary`<br>• Used for caches, breaking circular refs |\n",
"| 105 | Memory management? | Memory, arena, heap | • Python manages private heap<br>• pymalloc for small objects (<512 bytes)<br>• Pools and arenas for efficiency<br>• CPython reuses freed memory internally |\n",
"| 106 | Why avoid `__del__`? | __del__, destructor | • Timing is unpredictable<br>• Exceptions silently ignored<br>• Prevents GC of circular refs<br>• Use `with` / context managers instead<br>• Or `weakref.finalize()` |\n",
"| 107 | Truth value testing rules? | Truthy, falsy | • **Falsy**: `None`, `False`, `0`, `0.0`, `''`, `[]`, `()`, `{}`, `set()`<br>• Everything else is **truthy**<br>• Custom: define `__bool__()` or `__len__()`<br>• `bool(obj)` calls `__bool__` first, then `__len__` |\n",
"| 108 | What is monkey patching? | Monkey patching, runtime | • Dynamically modifying classes/modules at runtime<br>• `SomeClass.method = new_method`<br>• Used in testing (mocking)<br>• Pros: flexible, quick fixes<br>• Cons: hard to debug, fragile |\n",
"| 109 | Duck typing in depth? | Duck typing, Protocol | • Python cares about behavior, not type<br>• Any object with `read()` is 'file-like'<br>• Python 3.8+: `Protocol` for static duck typing<br>• Define expected methods without inheritance |\n",
"| 110 | `copy()` vs assignment? | Copy, assignment, ref | • Assignment: another reference to SAME object<br>• `copy.copy()`: new object, same nested refs (shallow)<br>• `copy.deepcopy()`: recursively copies everything<br>• Immutable → assignment fine; mutable nested → deepcopy |\n",
"| 111 | String methods? | String, split, join | • `split()`, `join()`, `strip()`, `replace()`<br>• `startswith()`, `endswith()`, `find()`, `count()`<br>• `upper()`, `lower()`, `title()`, `isdigit()`<br>• Strings immutable → methods return NEW strings |\n",
"| 112 | `__call__` and callable? | __call__, callable | • Makes instance callable like a function<br>• `class Counter: def __call__(self): self.n+=1`<br>• Check with `callable(obj)`<br>• Used for stateful functions |\n",
"| 113 | `__getattr__` vs `__getattribute__`? | __getattr__, attribute | • `__getattribute__` → called for EVERY access<br>• `__getattr__` → called ONLY when lookup fails<br>• Use `__getattr__` for dynamic attributes<br>• Avoid `__getattribute__` (infinite recursion risk) |\n",
"| 114 | Python descriptors? | Descriptor, __get__ | • Objects with `__get__`, `__set__`, `__delete__`<br>• Powers `@property`, `@classmethod`, `@staticmethod`<br>• Data descriptor (`__set__`) > instance dict<br>• Key to Python's attribute lookup |\n",
"| 115 | `enum` module? | Enum, IntEnum, auto | • `class Color(Enum): RED=1; GREEN=2`<br>• Type-safe, ordered, hashable, singletons<br>• `IntEnum` allows integer math<br>• `auto()` auto-assigns values<br>• Better than magic constants |\n",
"| 116 | Regular expressions (`re`)? | Regex, re, pattern | • `re.search(pattern, string)` → first match<br>• `re.findall()` → all matches<br>• `re.sub(pattern, repl, string)` → replace<br>• `re.compile()` → pre-compile for reuse<br>• Common: `\\d+`, `\\w+`, `[a-z]+`, `^…$` |\n",
"| 117 | `logging` module? | Logging, DEBUG, INFO | • Levels: DEBUG < INFO < WARNING < ERROR < CRITICAL<br>• `logger = logging.getLogger(__name__)`<br>• Handlers: file, console, email<br>• Always use logging, not print, in production |\n",
"| 118 | `datetime` module? | datetime, timedelta | • `datetime.now()`, `date.today()`<br>• `timedelta(days=7)` → duration<br>• `strftime('%Y-%m-%d')` → format to string<br>• `strptime('2024-01-01', '%Y-%m-%d')` → parse<br>• Use `timezone.utc` for awareness |\n",
"| 119 | Virtual environments? | venv, isolation | • Isolated Python with own packages<br>• `python -m venv myenv`<br>• `source myenv/bin/activate` (Unix)<br>• `pip freeze > requirements.txt`<br>• Essential for dependency management |\n",
"| 120 | `pip` and `requirements.txt`? | pip, package | • `pip install package`, `pip install -r requirements.txt`<br>• Pin exact versions: `requests==2.31.0`<br>• Always use virtual environments<br>• Modern: `poetry` or `pipenv` |\n",
"| 121 | `__name__ == '__main__'`? | __name__, main | • `__name__` = `'__main__'` when run directly<br>• `__name__` = module name when imported<br>• Guard prevents code running on import<br>• Reusable code above, script logic in guard |\n",
"| 122 | Module vs Package? | Module, package, __init__ | • **Module**: single `.py` file<br>• **Package**: directory with `__init__.py`<br>• Packages organize related modules<br>• `from package import module` |\n",
"| 123 | `*` and `**` in definitions? | Star, positional-only | • `*args` → positional args as tuple<br>• `**kwargs` → keyword args as dict<br>• `def f(a, /, b, *, c):`<br>  → `a` positional-only, `c` keyword-only<br>• Unpack: `f(*list)`, `f(**dict)` |\n",
"| 124 | Method chaining? | Chaining, fluent | • `obj.filter(x).sort().take(5)`<br>• Return `self` from each method<br>• Common in Pandas, SQLAlchemy<br>• Builder pattern |\n",
"| 125 | `functools.wraps`? | wraps, decorator | • Preserves original `__name__`, `__doc__`, `__module__`<br>• Use in every decorator: `@wraps(func)`<br>• Without it, decorated function appears as wrapper |\n",
]),

# ─── Section F: Q126-150 ───
md([
"---\n","\n",
"#### Section F: Testing, Modules & Standard Library (Q126–150)\n",
"\n",
"| # | Question | Keywords | Answer |\n",
"|---|----------|----------|--------|\n",
"| 126 | Unit testing? | unittest, pytest | • Verifies individual functions work correctly<br>• `unittest`: class-based, `TestCase`, `assertEqual`<br>• `pytest`: function-based, plain `assert`, fixtures<br>• Run: `pytest test_module.py -v` |\n",
"| 127 | `unittest` vs `pytest`? | unittest, pytest | • `unittest`: class-based, built-in, verbose<br>• `pytest`: function-based, simpler, better output<br>• `pytest` has fixtures, parametrize, plugins<br>• `pytest` is industry standard |\n",
"| 128 | Mocking in tests? | Mock, patch | • `unittest.mock.Mock()` → fake objects<br>• `@patch('module.func')` → replace during tests<br>• `mock.return_value = 42`<br>• `mock.assert_called_with(arg)`<br>• Isolate units from external deps |\n",
"| 129 | TDD? | TDD, red-green-refactor | • **Red**: write failing test<br>• **Green**: write minimal code to pass<br>• **Refactor**: clean up while tests pass<br>• Write tests BEFORE code |\n",
"| 130 | Fixtures in pytest? | Fixture, setup | • `@pytest.fixture def db(): yield conn; conn.close()`<br>• Tests receive fixture by parameter name<br>• Scopes: function, class, module, session<br>• `conftest.py` shares fixtures |\n",
"| 131 | `assert` statement? | Assert, debugging | • `assert expr, msg` → AssertionError if falsy<br>• Removed with `-O` flag<br>• For debugging invariants only<br>• **Never** for production validation |\n",
"| 132 | Module vs package vs library? | Module, library, framework | • **Module**: single .py file<br>• **Package**: directory + `__init__.py`<br>• **Library**: collection of packages (NumPy)<br>• **Framework**: controls flow (Django) |\n",
"| 133 | How does Python find modules? | sys.path, import | • Searches: current dir → PYTHONPATH → defaults<br>• `sys.path` lists search directories<br>• Can modify: `sys.path.append('/path')` |\n",
"| 134 | `__all__`? | __all__, public API | • Names exported by `from module import *`<br>• `__all__ = ['func1', 'Class1']`<br>• Hidden from `import *` but still importable directly |\n",
"| 135 | `abc` module? | ABC, abstract | • `from abc import ABC, abstractmethod`<br>• Abstract classes can't be instantiated<br>• Subclasses MUST implement `@abstractmethod`s<br>• Defines interfaces and contracts |\n",
"| 136 | `typing` module? | typing, generics | • `List[int]`, `Dict[str, int]`, `Optional[str]`<br>• `Callable[[int], str]`, `TypeVar('T')`<br>• `Protocol` for structural subtyping<br>• Python 3.9+: `list[int]`; 3.10+: `int \\| str` |\n",
"| 137 | `heapq`? | heapq, priority queue | • Min-heap: `heappush(h, val)`, `heappop(h)`<br>• Max-heap: negate values<br>• `nlargest(n, iter)`, `nsmallest(n, iter)`<br>• O(log n) push/pop<br>• Use for top-K, scheduling, Dijkstra |\n",
"| 138 | `bisect`? | bisect, binary search | • Binary search on sorted lists<br>• `bisect.bisect(a, x)` → insertion point<br>• `bisect.insort(a, x)` → insert maintaining sort<br>• O(log n) search |\n",
"| 139 | `hashlib`? | hashlib, SHA256 | • Cryptographic hashing: `hashlib.sha256(b'data').hexdigest()`<br>• SHA-256, SHA-512 (MD5 insecure)<br>• Passwords, file integrity, dedup<br>• Hashing is one-way, not encryption |\n",
"| 140 | Decorators with arguments? | Decorator, factory | • Three levels: `def repeat(n): def deco(fn): @wraps(fn) def wrap(*a): … return wrap return deco`<br>• Usage: `@repeat(3) def hello(): …`<br>• Outer function receives decorator args |\n",
"| 141 | `@lru_cache`? | lru_cache, memoize | • `@lru_cache(maxsize=128)` → cache results<br>• LRU evicts oldest when full<br>• `maxsize=None` → unlimited<br>• `.cache_info()` shows hits/misses<br>• Python 3.9+: `@cache` |\n",
"| 142 | `@contextmanager`? | contextlib, yield | • `@contextmanager def timer(): start=time(); yield; print(elapsed)`<br>• `yield` separates setup and cleanup<br>• Simpler than `__enter__/__exit__`<br>• `suppress(Error)` to ignore exceptions |\n",
"| 143 | `dataclasses.field`? | field, default_factory | • `field(default_factory=list)` → mutable defaults<br>• **Never** `field=[]` (shared reference!)<br>• `repr=False`, `compare=False`, `init=False`<br>• Fine-grained field control |\n",
"| 144 | `__slots__` when to use? | __slots__, memory | • `__slots__ = ['x', 'y']` replaces `__dict__`<br>• 20-30% less memory per instance<br>• Can't add dynamic attributes<br>• Use with millions of instances |\n",
"| 145 | `struct` module? | struct, binary | • Converts Python values ↔ C structs (bytes)<br>• `struct.pack('2i', 1, 2)` → bytes<br>• `struct.unpack('2i', data)` → tuple<br>• For binary files, network protocols |\n",
"| 146 | `inspect` module? | inspect, introspection | • `inspect.signature(func)` → parameters<br>• `inspect.getsource(func)` → source code<br>• `inspect.getmembers(obj)` → all attributes<br>• Used in debugging and frameworks |\n",
"| 147 | `__contains__` and `in`? | __contains__, in | • `__contains__` customizes `in` operator<br>• Without it: Python iterates via `__iter__`<br>• set/dict `in` is O(1); list is O(n) |\n",
"| 148 | `is None` vs `== None`? | is None, identity | • `is None` — identity check (exact None object)<br>• `== None` — calls `__eq__` (overridable)<br>• Always use `is None` (faster, unambiguous)<br>• PEP 8 recommends `is None` |\n",
"| 149 | `@property` in depth? | property, getter | • Getter: `@property def name(self):`<br>• Setter: `@name.setter def name(self, val):`<br>• Deleter: `@name.deleter def name(self):`<br>• Attribute-style access with method-level control |\n",
"| 150 | `__hash__` implementation? | __hash__, hashable | • Returns integer hash for dict keys / set elements<br>• If you define `__eq__`, MUST define `__hash__`<br>• `a == b` implies `hash(a) == hash(b)`<br>• Set to None for unhashable objects |\n",
]),

# ─── Section G: Q151-175 ───
md([
"---\n","\n",
"#### Section G: Data Structures & Algorithm Patterns (Q151–175)\n",
"\n",
"| # | Question | Keywords | Answer |\n",
"|---|----------|----------|--------|\n",
"| 151 | Big O notation? | Big O, time complexity | • O(1) constant → O(log n) → O(n) → O(n log n) → O(n²) → O(2ⁿ)<br>• List: append O(1), insert O(n), `in` O(n)<br>• Dict/Set: get/set/`in` O(1) average<br>• Always prefer dict/set for lookups |\n",
"| 152 | Python operation complexities? | Complexity, list, dict | • **List**: index O(1), append O(1), insert/pop(0) O(n), sort O(n log n)<br>• **Dict**: get/set/del O(1) avg<br>• **Set**: add/remove/`in` O(1) avg<br>• **Deque**: appendleft/popleft O(1) |\n",
"| 153 | Stack implementation? | Stack, LIFO | • Last In, First Out (LIFO)<br>• `push = list.append()`, `pop = list.pop()`<br>• `peek = list[-1]`<br>• Or `collections.deque`<br>• Use for: undo, bracket matching, DFS |\n",
"| 154 | Queue implementation? | Queue, FIFO, deque | • First In, First Out (FIFO)<br>• **Don't** use list (`pop(0)` is O(n))<br>• Use `collections.deque`: appendleft + pop<br>• `queue.Queue` for thread-safe<br>• Priority: `heapq` |\n",
"| 155 | Linked list in Python? | Linked list, node | • No built-in — `list` is dynamic array<br>• Manual: `class Node: val, next`<br>• `deque` is doubly-linked internally<br>• Asked in interviews, rarely used in production |\n",
"| 156 | Hash table / dict internals? | Hash table, dict | • Maps keys to values via hash function<br>• Open addressing for collisions<br>• Keys must be hashable<br>• Average O(1) lookup/insert/delete<br>• Compact layout since Python 3.6 |\n",
"| 157 | Sorting algorithms? | Sorting, TimSort | • **TimSort** (Python built-in): O(n log n), stable<br>• **Bubble Sort**: O(n²), stable<br>• **Merge Sort**: O(n log n), stable, O(n) space<br>• **Quick Sort**: O(n log n) avg, O(n²) worst<br>• `sorted()` and `.sort()` use TimSort |\n",
"| 158 | Binary search? | Binary search, O(log n) | • Find value in sorted list by halving<br>• O(log n) — requires sorted input<br>• Python: `bisect.bisect_left(list, target)`<br>• Manual: `while lo <= hi: mid = (lo+hi)//2` |\n",
"| 159 | Recursion vs Iteration? | Recursion, iteration | • Recursion: elegant for trees/graphs, uses call stack<br>• Iteration: loops, memory-efficient, no overflow<br>• Every recursion → iterative with explicit stack<br>• Python limit ~1000 recursive calls |\n",
"| 160 | Dynamic programming? | DP, memoize, tabulation | • Overlapping subproblems + optimal substructure<br>• **Top-down**: recursion + `@lru_cache`<br>• **Bottom-up**: iterative table filling<br>• Examples: Fibonacci, knapsack, coin change |\n",
"| 161 | BFS vs DFS? | BFS, DFS, graph | • **BFS**: queue, level-by-level, shortest path<br>• **DFS**: stack/recursion, deep-first<br>• BFS for shortest path, level-order<br>• DFS for path existence, cycle detection, topological sort |\n",
"| 162 | Two-pointer technique? | Two pointer, O(n) | • Iterate from both ends or different speeds<br>• Palindrome, two-sum (sorted), container problem<br>• Fast/slow for cycle detection (Floyd's)<br>• O(n) instead of O(n²) |\n",
"| 163 | Sliding window? | Sliding window, O(n) | • Maintain window while iterating<br>• Fixed: max sum of k elements<br>• Variable: longest substring without repeats<br>• Subarray/substring problems |\n",
"| 164 | Cycle detection? | Floyd's, tortoise-hare | • Slow pointer (1 step) + fast pointer (2 steps)<br>• If they meet → cycle exists<br>• Find start: reset slow to head, both move 1<br>• O(n) time, O(1) space |\n",
"| 165 | What is a trie? | Trie, prefix tree | • Stores strings char by char with shared prefixes<br>• O(m) lookup (m = word length)<br>• Used for autocomplete, spell check, IP routing<br>• Python: nested dicts or `class TrieNode` |\n",
"| 166 | Memoization vs tabulation? | Memoization, tabulation | • **Memoization** (top-down): recursive, cache results<br>• **Tabulation** (bottom-up): iterative, fill table<br>• Memoization easier (`@lru_cache`)<br>• Tabulation avoids recursion limits |\n",
"| 167 | Interview coding patterns? | Coding patterns | • Two pointers, Sliding window<br>• Binary search, BFS/DFS<br>• Dynamic programming, Backtracking<br>• Heap/priority queue, Hashing<br>• Monotonic stack, Tree traversal |\n",
"| 168 | Min/Max heap? | Heap, heapq | • `heapq.heappush(h, val)`, `heapq.heappop(h)` → min<br>• Max-heap: negate values<br>• Min without removing: `h[0]`<br>• `heapify(list)` in O(n)<br>• Top-K, merge K sorted, scheduling |\n",
"| 169 | What is backtracking? | Backtracking, pruning | • Explore all solutions incrementally<br>• **Choose → Explore → Unchoose**<br>• Prune invalid candidates early<br>• N-Queens, sudoku, permutations, word search |\n",
"| 170 | Graph representation? | Graph, adjacency list | • **Adjacency list** (dict of lists): `{'A':['B','C']}`<br>  → O(V+E) space, preferred<br>• **Adjacency matrix** (2D list): O(V²) space<br>• Use `defaultdict(list)` |\n",
"| 171 | Reverse a linked list? | Reverse, linked list | • Three pointers: prev=None, curr=head, next<br>• Each step: save next, reverse pointer, advance<br>• Return prev<br>• O(n) time, O(1) space |\n",
"| 172 | `array` vs `list` vs NumPy? | array, list, numpy | • `list`: any type, dynamic, general purpose<br>• `array.array`: single type, less memory<br>• `numpy.ndarray`: vectorized, contiguous, 10-100x faster<br>• Use NumPy for numerical computation |\n",
"| 173 | `defaultdict` vs dict? | defaultdict, KeyError | • `dict` raises `KeyError` on missing keys<br>• `defaultdict(factory)` auto-creates default<br>• Factories: `int` (count), `list` (group), `set`<br>• Equivalent to `dict.setdefault()` but cleaner |\n",
"| 174 | OrderedDict still needed? | OrderedDict, order | • Regular dict preserves order since Python 3.7<br>• OrderedDict extras: `move_to_end()`<br>• Equality considers order (dict doesn't)<br>• Can be reversed |\n",
"| 175 | `string` module? | string, constants | • `string.ascii_letters`, `string.digits`<br>• `string.punctuation`, `string.ascii_lowercase`<br>• `string.Template('Hello $name')`<br>• Useful for random strings, validation |\n",
]),

# ─── Section H: Q176-200 ───
md([
"---\n","\n",
"#### Section H: Design Patterns, Real-World & Data Science (Q176–200)\n",
"\n",
"| # | Question | Keywords | Answer |\n",
"|---|----------|----------|--------|\n",
"| 176 | Design patterns in Python? | Singleton, Factory | • **Creational**: Singleton, Factory, Builder<br>• **Structural**: Adapter, Decorator, Facade<br>• **Behavioral**: Observer, Strategy, Iterator<br>• Python's dynamism simplifies many patterns |\n",
"| 177 | Singleton pattern? | Singleton, single instance | • Ensures only one instance exists<br>• Python: use module (simplest), or `__new__` override<br>• Or `@lru_cache` on factory function<br>• Module-level is the Pythonic way |\n",
"| 178 | Factory pattern? | Factory, classmethod | • Creates objects without specifying exact class<br>• `@classmethod def from_json(cls, data): return cls(**data)`<br>• Decouples creation from usage |\n",
"| 179 | Observer pattern? | Observer, event | • Subjects notify observers on state changes<br>• Python: callbacks list, signals library<br>• UI components reacting to data changes |\n",
"| 180 | Iterator pattern? | Iterator, __iter__ | • Built-in Python support via `__iter__` + `__next__`<br>• Generators are simplest iterators<br>• `for` loop, `list()`, `sum()` all use iterator protocol |\n",
"| 181 | Strategy pattern? | Strategy, callable | • Swap algorithms at runtime<br>• In Python: just pass functions<br>• `def sort_data(data, strategy=sorted):`<br>• First-class functions make it trivial |\n",
"| 182 | Decorator pattern vs @? | Decorator, structural | • **Pattern**: wraps object to add behavior<br>• **@syntax**: wraps function<br>• `@decorator` IS the Decorator pattern for functions<br>• Both add behavior without modifying original |\n",
"| 183 | What is a coroutine? | Coroutine, async def | • Function that can be suspended and resumed<br>• `async def` defines, `await` pauses<br>• Cooperative (yield control explicitly)<br>• Single-threaded, non-blocking I/O |\n",
"| 184 | `asyncio.gather`? | gather, concurrent | • Runs multiple coroutines concurrently<br>• `results = await asyncio.gather(a(), b(), c())`<br>• Returns results in order<br>• `return_exceptions=True` catches errors |\n",
"| 185 | Event loop? | Event loop, asyncio | • Core of asyncio — runs coroutines<br>• `asyncio.run(main())` creates and runs loop<br>• One loop per thread<br>• Never block with CPU-heavy work<br>• Use `run_in_executor()` for blocking code |\n",
"| 186 | `concurrent.futures`? | ThreadPool, ProcessPool | • `ThreadPoolExecutor` → I/O-bound<br>• `ProcessPoolExecutor` → CPU-bound<br>• `executor.map(func, items)` → distribute work<br>• `submit()` returns `Future` objects |\n",
"| 187 | `multiprocessing.Pool`? | Pool, parallel | • `Pool(4)` creates process pool<br>• `pool.map(func, iter)` → true parallelism<br>• Each process has own GIL<br>• Data serialized (pickled) between processes |\n",
"| 188 | What is NumPy? | NumPy, ndarray | • N-dimensional arrays with vectorized ops<br>• 10-100x faster than lists for math<br>• Broadcasting, fancy indexing, linear algebra<br>• Core of scientific Python stack |\n",
"| 189 | What is Pandas? | Pandas, DataFrame | • `DataFrame` (2D table) and `Series` (1D)<br>• `read_csv()`, `groupby()`, `merge()`<br>• `pivot_table()`, `fillna()`, `apply()`<br>• Essential for data analysis |\n",
"| 190 | NumPy array vs list? | NumPy, list, perf | • NumPy: fixed type, contiguous, vectorized, fast<br>• List: mixed types, pointers, needs loops<br>• NumPy supports broadcasting<br>• 10-100x speed difference for math |\n",
"| 191 | Flask vs Django? | Flask, Django | • **Flask**: micro, minimal, flexible, good for APIs<br>• **Django**: full-featured, ORM, admin, auth, templates<br>• Flask for freedom; Django for rapid full-stack |\n",
"| 192 | REST API in Python? | REST, FastAPI | • HTTP methods: GET, POST, PUT, DELETE<br>• Frameworks: Flask, FastAPI, DRF<br>• FastAPI: async, auto-docs, type-validated<br>• Return JSON with status codes |\n",
"| 193 | `__getitem__`/`__setitem__`? | __getitem__, indexing | • `__getitem__` → `obj[key]`<br>• `__setitem__` → `obj[key] = val`<br>• `__delitem__` → `del obj[key]`<br>• Enables custom sequences/mappings |\n",
"| 194 | TensorFlow vs PyTorch? | TF, PyTorch, DL | • **TensorFlow**: Google, production-focused, TFLite<br>• **PyTorch**: Meta, research-friendly, dynamic graph<br>• PyTorch dominates research<br>• TensorFlow dominates production |\n",
"| 195 | List vs generator memory? | Generator, memory | • 1M ints: list ≈ 8MB, generator ≈ 120 bytes<br>• Gen computes on-the-fly (lazy)<br>• `sum(x**2 for x in range(10**6))` → O(1) memory<br>• Always prefer generators for large data |\n",
"| 196 | `timeit` module? | timeit, benchmark | • `timeit.timeit('code', number=1000)`<br>• More accurate than `time.time()`<br>• Disables GC, runs multiple iterations<br>• Jupyter: `%timeit expression` |\n",
"| 197 | `__enter__`/`__exit__`? | __enter__, __exit__ | • `__enter__` → setup, return resource<br>• `__exit__(exc_type, exc_val, exc_tb)` → cleanup<br>• Return True from `__exit__` to suppress exceptions<br>• `exc_type` is None if no exception |\n",
"| 198 | `sys.getsizeof()`? | getsizeof, memory | • Returns memory size in bytes (shallow only)<br>• Deep size: use `pympler.asizeof()`<br>• `getsizeof([])` → 56 bytes<br>• `getsizeof({})` → 64 bytes |\n",
"| 199 | `__repr__` vs `__str__` rule? | __repr__, __str__ | • `__repr__` → developers (unambiguous)<br>• `__str__` → users (readable)<br>• `repr()` calls `__repr__`; `print()` calls `__str__`<br>• Implement `__repr__` first (fallback for `__str__`) |\n",
"| 200 | Production Python checklist? | Best practices | • Follow PEP 8 (use `black`)<br>• Type hints + `mypy`<br>• Write docstrings + tests (pytest)<br>• Use logging, not print<br>• Virtual environments + pin deps<br>• Context managers for resources<br>• Profile before optimizing (`cProfile`, `timeit`) |\n",
]),
]

with open(NB,"r") as f: nb=json.load(f)
nb["cells"].extend(C)
with open(NB,"w") as f: json.dump(nb,f,indent=1,ensure_ascii=False)
print(f"Added {len(C)} cells (Q101-200). Total: {len(nb['cells'])}")
